version: "3"

services:
  web_service:
    build: .
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000" ]
    expose:
      - "5000"
    depends_on:
      - pgpool
    restart: always
    deploy:
      replicas: 4

  nginx:
    build: nginx/.
    depends_on:
      - web_service
    ports:
      - "8000:80"
  pgprimary:
    container_name: base_postgres
    image: bitnami/postgresql
    ports:
      - 5432
    volumes:
      - pgprimary_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=s3cret
      - POSTGRESQL_PASSWORD=s3cret
      - POSTGRESQL_DATABASE=test_db
  pgreplica:
    image: bitnami/postgresql
    ports:
      - 5432
    depends_on:
      - pgprimary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=s3cret
      - POSTGRESQL_MASTER_HOST=pgprimary
      - POSTGRESQL_PASSWORD=s3cret
  pgreplica1:
    image: bitnami/postgresql
    ports:
      - 5432
    depends_on:
      - pgprimary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=s3cret
      - POSTGRESQL_MASTER_HOST=pgprimary
      - POSTGRESQL_PASSWORD=s3cret

  pgreplica2:
    image: bitnami/postgresql
    ports:
      - 5432
    depends_on:
      - pgprimary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=postgres
      - POSTGRESQL_REPLICATION_PASSWORD=s3cret
      - POSTGRESQL_MASTER_HOST=pgprimary
      - POSTGRESQL_PASSWORD=s3cret
  pgpool:
    image: bitnami/pgpool
    ports:
      - 5432:5432
    depends_on:
      - pgprimary
    environment:
      - PGPOOL_BACKEND_NODES=0:pgprimary:5432:0:primary:ALWAYS_PRIMARY,1:pgreplica:5432:5:replica,2:pgreplica1:5432:5:replica,3:pgreplica2:5432:5:replica
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=s3cret
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=s3cret
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
      - PGPOOL_NUM_INIT_CHILDREN=10
      - PGPOOL_MAX_POOL=10000
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=s3cret
volumes:
  pgprimary_data: